version: '2'
services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://keyauthservice-postgresql:5432/keyauthservice
    ports:
      - "8080:8080"
    depends_on:
      - keyauthservice-postgresql
    links:
      - keyauthservice-postgresql
    volumes:
      - /tmp:/tmp
  keyauthservice-postgresql:
    extends:
      file: postgres.yaml
      service: keyauthservice-postgresql
volumes:
  logvolume01: {}
