version: '2'
services:

  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile-devel
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://keyauthservice-postgresql:5432/keyauthservice
      - SPRING_REDIS_HOST=keyauthservice-redis
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
    depends_on:
      - keyauthservice-postgresql
      - keyauthservice-redis
      - keyauthservice-keyclock
    links:
      - keyauthservice-postgresql
      - keyauthservice-redis
      - keyauthservice-keyclock
    volumes:
      - /tmp:/tmp

  keyauthservice-react:
    build:
      context: ../
      dockerfile: Dockerfile-angular
    volumes:
      - '../src/main/webapp:/app'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
  keyauthservice-postgresql:
    extends:
      file: postgres.yaml
      service: keyauthservice-postgresql

  keyauthservice-redis:
    extends:
      file: redis.yaml
      service: redis

  keyauthservice-keyclock:
    extends:
      service: keycloak
      file: keycloak.yaml
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keyauthservice-keyclock-postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd

    depends_on:
      - keyauthservice-keyclock-postgres
    links:
      - keyauthservice-keyclock-postgres
  keyauthservice-keyclock-postgres:
    extends:
      service: postgres
      file: keycloak.yaml



volumes:
  logvolume01: {}
