version: '2'
services:

  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile-prod
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://keyauthservice-postgresql:5432/keyauthservice
      - SPRING_REDIS_HOST=keyauthservice-redis
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8080:8080"
    depends_on:
      - keyauthservice-postgresql
      - keyauthservice-redis
      - keyauthservice-keyclock
    links:
      - keyauthservice-postgresql
      - keyauthservice-redis
      - keyauthservice-keyclock
    volumes:
      - /tmp:/tmp

  keyauthservice-postgresql:
    extends:
      file: postgres.yaml
      service: keyauthservice-postgresql

  keyauthservice-redis:
    extends:
      file: redis.yaml
      service: redis


volumes:
  logvolume01: {}
  postgres: {}
  postgres_data: {}
