version: '2.1'
services:
  keyauthservice-postgresql:
    image: postgres:12
    volumes:
         - postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=keyauthservice
      - POSTGRES_PASSWORD=keyauthservice
      - PGDATA=/var/lib/postgresql/data/pgdata

    ports:
      - 5432:5432

volumes:
  postgres:
    external: true
